import "./globals.css";
import type { Metadata } from "next";
import { Inter, Gloock, Poppins } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const gloock = Gloock({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-gloock",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
